#!/bin/bash

[ $# == 1 ] || exit 1

pass=''
i=0
while [ $i -lt $1 ]
do
    unset char
    while [ -z "$char" ]
    do
        char=$(dd if=/dev/urandom bs=1 count=1 2>/dev/null | tr -dc '0-9a-zA-Z,.~@£$%^&+=_-' 2>/dev/null)
    done
    pass="$pass$char"
    (( i++ ))
done
echo $pass
